spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myrctc
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: user
      password: $2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /api

myrctc:
  auth:
    token:
      expiration-duration: 120000
      secret: r3pl4c3M3InPr0d
server:
  port: 8081