CREATE TABLE IF NOT EXISTS Station (
    station_code VARCHAR(4) PRIMARY KEY,
    station_name VARCHAR(100)
);
INSERT INTO Station (station_code, station_name) VALUES
-- Northern Zone & NCR
('NDLS', 'New Delhi'),
('DLI', 'Old Delhi Junction'),
('NZM', 'Hazrat Nizamuddin'),
('ANVT', 'Anand Vihar Terminal'),
('DEC', 'Delhi Cantt'),
('DEE', 'Delhi Sarai Rohilla'),
('CDG', 'Chandigarh Junction'),
('ASR', 'Amritsar Junction'),
('LDH', 'Ludhiana Junction'),
('UMB', 'Ambala Cantt Junction'),
('JAT', 'Jammu Tawi'),
('SVDK', 'Shri Mata Vaishno Devi Katra'),
('HW', 'Haridwar'),
('DDN', 'Dehradun'),
('KGM', 'Kathgodam'),
('LKO', 'Lucknow Charbagh'),
('LJN', 'Lucknow Junction NER'),
('CNB', 'Kanpur Central'),
('BSB', 'Varanasi Junction'),
('BSBS', 'Banaras'),
('ALJN', 'Aligarh Junction'),
('AGC', 'Agra Cantt'),
('AF', 'Agra Fort'),
('GWL', 'Gwalior Junction'),
('VGLJ', 'Virangana Lakshmibai Jhansi'),
('PRYJ', 'Prayagraj Junction'),
('PYGS', 'Prayagraj Sangam'),
('AY', 'Ayodhya Dham Junction'),
('AYC', 'Ayodhya Cantt'),
('GKP', 'Gorakhpur Junction'),
('CPR', 'Chhapra Junction'),
('MFP', 'Muzaffarpur Junction'),
('SPJ', 'Samastipur Junction'),
('DBG', 'Darbhanga Junction'),
('BJU', 'Barauni Junction'),
('PNBE', 'Patna Junction'),
('RJPB', 'Rajendra Nagar Terminal'),
('DNR', 'Danapur'),
('KGG', 'Khagaria Junction'),
('KIR', 'Katihar Junction'),
('JP', 'Jaipur Junction'),
('JU', 'Jodhpur Junction'),
('BKN', 'Bikaner Junction'),
('UDZ', 'Udaipur City'),
('KOTA', 'Kota Junction'),
('COR', 'Chittaurgarh Junction'),
('AII', 'Ajmer Junction'),
('ABR', 'Abu Road'),
('RE', 'Rewari Junction'),
('MB', 'Moradabad Junction'),
('BE', 'Bareilly Junction'),
('SRE', 'Saharanpur Junction'),
('PTA', 'Patiala'),
('BTI', 'Bathinda Junction'),
('KLK', 'Kalka'),
('RTM', 'Ratlam Junction'),
('DHD', 'Dahod'),

-- Western Zone & Central Zone
('CSMT', 'Chhatrapati Shivaji Maharaj Terminus'),
('DR', 'Dadar Central'),
('LTT', 'Lokmanya Tilak Terminus'),
('MMCT', 'Mumbai Central'),
('BDTS', 'Bandra Terminus'),
('BVI', 'Borivali'),
('PUNE', 'Pune Junction'),
('STR', 'Satara'),
('MRJ', 'Miraj Junction'),
('KOP', 'Chhatrapati Shahu Maharaj Terminus Kolhapur'),
('BSL', 'Bhusaval Junction'),
('KNW', 'Khandwa Junction'),
('NGP', 'Nagpur Junction'),
('BPQ', 'Balharshah Junction'),
('ADI', 'Ahmedabad Junction'),
('BRC', 'Vadodara Junction'),
('ST', 'Surat'),
('VAPI', 'Vapi'),
('BL', 'Valsad'),
('ANND', 'Anand Junction'),
('NHD', 'Nadiad Junction'),
('RJT', 'Rajkot Junction'),
('HAPA', 'Hapa'),
('JAM', 'Jamnagar'),
('BVC', 'Bhavnagar Terminus'),
('GIMB', 'Gandhidham Junction'),
('BPL', 'Bhopal Junction'),
('RKMP', 'Rani Kamalapati'),
('ET', 'Itarsi Junction'),
('JBP', 'Jabalpur Junction'),
('KTE', 'Katni Junction'),
('STA', 'Satna Junction'),
('BINA', 'Bina Junction'),
('SHRN', 'Sant Hirdaram Nagar'),
('UJN', 'Ujjain Junction'),
('INDB', 'Indore Junction'),
('AK', 'Akola Junction'),
('BD', 'Badnera Junction'),
('WR', 'Wardha Junction'),
('NK', 'Nashik Road'),
('MMR', 'Manmad Junction'),
('SUR', 'Solapur Junction'),
('KWV', 'Kurduwadi Junction'),

-- Southern Zone & South Western
('MAS', 'MGR Chennai Central'),
('MS', 'Chennai Egmore'),
('PER', 'Perambur'),
('TBM', 'Tambaram'),
('CGL', 'Chengalpattu Junction'),
('AJJ', 'Arakkonam Junction'),
('KPD', 'Katpadi Junction'),
('JTJ', 'Jolarpettai Junction'),
('SA', 'Salem Junction'),
('ED', 'Erode Junction'),
('TUP', 'Tiruppur'),
('CBE', 'Coimbatore Junction'),
('PGT', 'Palakkad Junction'),
('SRR', 'Shoranur Junction'),
('CLT', 'Kozhikode Main'),
('CAN', 'Kannur'),
('MAQ', 'Mangaluru Central'),
('MAJN', 'Mangaluru Jn'),
('TCR', 'Thrissur'),
('ERS', 'Ernakulam Junction'),
('ERN', 'Ernakulam Town'),
('ALLP', 'Alappuzha'),
('TVC', 'Thiruvananthapuram Central'),
('NCJ', 'Nagercoil Junction'),
('MDU', 'Madurai Junction'),
('DG', 'Dindigul Junction'),
('TPJ', 'Tiruchchirappalli Junction'),
('TJ', 'Thanjavur Junction'),
('MV', 'Mayiladuturai Junction'),
('TEN', 'Tirunelveli Junction'),
('RMM', 'Rameswaram'),
('SBC', 'KSR Bengaluru City Junction'),
('YPR', 'Yesvantpur Junction'),
('SMVB', 'Sir M. Visvesvaraya Terminal Bengaluru'),
('MYS', 'Mysuru Junction'),
('UBL', 'SSS Hubballi Junction'),
('UBN', 'Karwar'),
('BGM', 'Belagavi'),
('DVG', 'Davangere'),
('ASK', 'Arsikere Junction'),
('BAY', 'Ballari Junction'),
('MAO', 'Madgaon Junction'),
('KRMI', 'Karmali'),

-- South Central & Eastern Coast
('SC', 'Secunderabad Junction'),
('HYB', 'Hyderabad Deccan'),
('KCG', 'Kacheguda'),
('BZA', 'Vijayawada Junction'),
('GNT', 'Guntur Junction'),
('RJY', 'Rajahmundry'),
('VSKP', 'Visakhapatnam Junction'),
('VZM', 'Vizianagaram Junction'),
('CHE', 'Srikakulam Road'),
('TPTY', 'Tirupati'),
('RU', 'Renigunta Junction'),
('OGL', 'Ongole'),
('NLR', 'Nellore'),
('GDR', 'Gudur Junction'),
('R', 'Raipur Junction'),
('BSP', 'Bilaspur Junction'),
('DURG', 'Durg Junction'),
('RIG', 'Raigarh'),
('WL', 'Warangal'),
('KZJ', 'Kazipet Junction'),
('BMT', 'Begumpet'),

-- Eastern Zone, SE Zone & NE Frontier
('HWH', 'Howrah Junction'),
('SDAH', 'Sealdah'),
('KOAA', 'Kolkata Terminus'),
('SHM', 'Shalimar'),
('BWN', 'Barddhaman Junction'),
('DGR', 'Durgapur'),
('ASN', 'Asansol Junction'),
('MLDT', 'Malda Town'),
('NJP', 'New Jalpaiguri Junction'),
('GHY', 'Guwahati'),
('AGTL', 'Agartala'),
('KYQ', 'Kamakhya Junction'),
('APDJ', 'Alipur Duar Junction'),
('NOQ', 'New Alipurduar'),
('TATA', 'Tatanagar Junction'),
('CKP', 'Chakradharpur'),
('ROU', 'Rourkela Junction'),
('JSG', 'Jharsuguda Junction'),
('KGP', 'Kharagpur Junction'),
('BAL', 'Baleshwar'),
('CTC', 'Cuttack Junction'),
('BBS', 'Bhubaneswar'),
('PURI', 'Puri'),
('BAM', 'Brahmapur'),
('RNC', 'Ranchi Junction'),
('MURI', 'Muri Junction'),
('BKSC', 'Bokaro Steel City'),
('DHN', 'Dhanbad Junction'),
('DDU', 'Pt. Deen Dayal Upadhyaya Junction'),
('GAYA', 'Gaya Junction'),
('DBRG', 'Dibrugarh'),
('TSK', 'Tinsukia Junction'),
('SCL', 'Silchar'),

-- Intermediate & Regional Junctions
('AHA', 'Abhaipur'),
('ABKP', 'Ambikapur'),
('ABR', 'Abu Road'),
('AMH', 'Azamgarh'),
('ANG', 'Ahmednagar'),
('AN', 'Amalner'),
('ARA', 'Ara Junction'),
('BXR', 'Buxar'),
('BTI', 'Bathinda Junction'),
('BHI', 'Bhiwani Junction'),
('BHL', 'Bhilwara'),
('BKP', 'Bakhtiyarpur Junction'),
('BPRD', 'Barpeta Road'),
('BRLA', 'Bhiria Road'),
('BUP', 'Bariarpur'),
('BWT', 'Bangarapet Junction'),
('CHP', 'Chantra'),
('COR', 'Chittaurgarh Junction'),
('CRJ', 'Chittaranjan'),
('DAA', 'Datia'),
('DBB', 'Dhubri'),
('DHE', 'Dhirpur'),
('DLN', 'Dildarnagar Junction'),
('DMV', 'Dimapur'),
('DOR', 'Dundara'),
('DRD', 'Dahanu Road'),
('DUI', 'Dhuri Junction'),
('DVD', 'Duvvada'),
('FDB', 'Faridabad'),
('FKD', 'Farrukhabad Junction'),
('FTP', 'Fatehpur'),
('GDA', 'Godhra Junction'),
('GHD', 'Garhwa Road Junction'),
('GMD', 'Gudmidipaddi'),
('GNA', 'Goshala'),
('GOH', 'Garot'),
('GSD', 'Ghasida'),
('GTR', 'Grant Road'),
('HBD', 'Hoshangabad'),
('HDI', 'Haldia'),
('HJP', 'Hajipur Junction'),
('HKR', 'Hindumalkote'),
('HNL', 'Hingoli Deccan'),
('HPT', 'Hosapete Junction'),
('HSRA', 'Hosur'),
('HVR', 'Haveri'),
('JDB', 'Jagdalpur'),
('JHG', 'Jhingura'),
('JHS', 'Jhansi Junction'),
('JJR', 'Jhajjar'),
('JLS', 'Jalesar Road'),
('JMO', 'Jamirghata'),
('JMU', 'Jamui'),
('JOC', 'Joychandi Pahar Junction'),
('KBL', 'Koppal'),
('KCG', 'Kacheguda'),
('KDM', 'Karamadai'),
('KGG', 'Khagaria Junction'),
('KIM', 'Kim'),
('KKDI', 'Karaikkudi Junction'),
('KLBG', 'Kalaburagi Junction'),
('KMU', 'Kumbakonam'),
('KNE', 'KishanGanj'),
('KRH', 'Khairthal'),
('KRNT', 'Kurnool City'),
('KRR', 'Karur Junction'),
('KSG', 'Kishangarh'),
('KTYM', 'Kottayam'),
('KUN', 'Karnal'),
('KWV', 'Kurduvadi Junction'),
('LKU', 'Lalkuan Junction'),
('LMG', 'Lumding Junction'),
('LPI', 'Lingampalli'),
('MABA', 'Mandi Bamora'),
('MAKR', 'Bina Malkhedi Junction'),
('MBNR', 'Mahbubnagar'),
('MCI', 'Manchiryal'),
('MKP', 'Manikpur Junction'),
('MLN', 'Mailani Junction'),
('MTC', 'Meerut City Junction'),
('MUV', 'Banaras'),
('MWA', 'Mandi Dabwali'),
('MZZ', 'Mirzapur'),
('NBD', 'Najibabad Junction'),
('ND', 'Nadiad Junction'),
('NDB', 'Nandurbar'),
('NFL', 'Narkatiaganj Junction'),
('NIM', 'Nimach'),
('NKR', 'Nainpur Junction'),
('NLDA', 'Nalgonda'),
('NN', 'Nandura'),
('NPL', 'Nagalapalle'),
('NRL', 'Nellore'),
('NTH', 'Nathwana'),
('NVU', 'Nawalgund'),
('OKHA', 'Okha'),
('ON', 'Unnao Junction'),
('PBP', 'Pembarti'),
('PNP', 'Panipat Junction'),
('PRR', 'Purulia Junction'),
('PUD', 'Phagwara Junction'),
('PVP', 'Parvathipuram'),
('QLN', 'Kollam Junction'),
('RBL', 'Rae Bareli Junction'),
('RDG', 'Rayadurg Junction'),
('REWA', 'Rewa'),
('RGL', 'Rengali'),
('RGS', 'Ringas Junction'),
('RJL', 'Rajaldesar'),
('RMA', 'Ramganj Mandi Junction'),
('RMM', 'Rameswaram'),
('ROK', 'Rohtak Junction'),
('ROU', 'Rourkela Junction'),
('RPH', 'Rampurhat Junction'),
('RR', 'Ren'),
('RXL', 'Raxaul Junction'),
('SBC', 'KSR Bengaluru City'),
('SBP', 'Sambalpur Junction'),
('SGG', 'SultanGanj'),
('SGZ', 'Shamgarh'),
('SHG', 'Shahganj Junction'),
('SIKR', 'Sikar Junction'),
('SLN', 'Sultanpur Junction'),
('SOG', 'Suratgarh Junction'),
('SRNT', 'Sarnath'),
('SSA', 'Sirsa'),
('SWM', 'Sawai Madhopur Junction'),
('TATA', 'Tatanagar Junction'),
('TCR', 'Thrissur'),
('TDL', 'Tundla Junction'),
('TEL', 'Tenali Junction'),
('TGHD', 'Thangadh'),
('TIG', 'Titilagarh Junction'),
('TKK', 'Tirakol'),
('TMV', 'Tindivanam'),
('TNA', 'Thane'),
('TND', 'Tandur'),
('TSI', 'Tenkasi Junction'),
('TUP', 'Tiruppur'),
('TZR', 'Turavur'),
('UBL', 'Hubballi Junction'),
('UDL', 'Andal Junction'),
('UJH', 'Ujhani'),
('UMB', 'Ambala Cantt Junction'),
('UMD', 'Osmanabad'),
('UNA', 'Una Himachal'),
('VDA', 'Vasad Junction'),
('VGLJ', 'V Lakshmibai Jhansi'),
('VLY', 'Valliyur'),
('VRI', 'Vriddhachalam Junction'),
('VYN', 'Vatva'),
('WADI', 'Wadi Junction'),
('WTR', 'Wankaner Junction'),
('YAL', 'Yalvigi'),
('YNK', 'Yelahanka Junction'),
('ZAR', 'Arigada')
ON CONFLICT (station_code) DO NOTHING;